# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = avogadro-1.2.0

HEADERS = \
   $$PWD/avogadro/src/projectdelegates/atomdelegate.h \
   $$PWD/avogadro/src/projectdelegates/bonddelegate.h \
   $$PWD/avogadro/src/projectdelegates/labeldelegate.h \
   $$PWD/avogadro/src/projectdelegates/moleculedelegate.h \
   $$PWD/avogadro/src/projectdelegates/residuedelegate.h \
   $$PWD/avogadro/src/projectdelegates/selectiondelegate.h \
   $$PWD/avogadro/src/aboutdialog.h \
   $$PWD/avogadro/src/addenginedialog.h \
   $$PWD/avogadro/src/application.h \
   $$PWD/avogadro/src/detachedview.h \
   $$PWD/avogadro/src/editcommands.h \
   $$PWD/avogadro/src/enginecolorswidget.h \
   $$PWD/avogadro/src/engineitemdelegate.h \
   $$PWD/avogadro/src/engineitemmodel.h \
   $$PWD/avogadro/src/enginelistview.h \
   $$PWD/avogadro/src/engineprimitiveswidget.h \
   $$PWD/avogadro/src/engineviewwidget.h \
   $$PWD/avogadro/src/flattabwidget.h \
   $$PWD/avogadro/src/glgraphicsview.h \
   $$PWD/avogadro/src/importdialog.h \
   $$PWD/avogadro/src/mainwindow.h \
   $$PWD/avogadro/src/pluginitemmodel.h \
   $$PWD/avogadro/src/pluginlistview.h \
   $$PWD/avogadro/src/pluginsettings.h \
   $$PWD/avogadro/src/primitiveitemmodel.h \
   $$PWD/avogadro/src/primitivetreeview.h \
   $$PWD/avogadro/src/projecttreeeditor.h \
   $$PWD/avogadro/src/projecttreeitem.h \
   $$PWD/avogadro/src/projecttreemodel.h \
   $$PWD/avogadro/src/projecttreemodeldelegate.h \
   $$PWD/avogadro/src/savedialog.h \
   $$PWD/avogadro/src/settingsdialog.h \
   $$PWD/avogadro/src/updatecheck.h \
   $$PWD/avogadro/src/updatedialog.h \
   $$PWD/build/avogadro/src/config.h \
   $$PWD/build/libavogadro/include/avogadro/animation.h \
   $$PWD/build/libavogadro/include/avogadro/atom.h \
   $$PWD/build/libavogadro/include/avogadro/bond.h \
   $$PWD/build/libavogadro/include/avogadro/camera.h \
   $$PWD/build/libavogadro/include/avogadro/color.h \
   $$PWD/build/libavogadro/include/avogadro/color3f.h \
   $$PWD/build/libavogadro/include/avogadro/colorbutton.h \
   $$PWD/build/libavogadro/include/avogadro/config.h \
   $$PWD/build/libavogadro/include/avogadro/cube.h \
   $$PWD/build/libavogadro/include/avogadro/dockextension.h \
   $$PWD/build/libavogadro/include/avogadro/dockwidget.h \
   $$PWD/build/libavogadro/include/avogadro/elementtranslator.h \
   $$PWD/build/libavogadro/include/avogadro/engine.h \
   $$PWD/build/libavogadro/include/avogadro/extension.h \
   $$PWD/build/libavogadro/include/avogadro/fragment.h \
   $$PWD/build/libavogadro/include/avogadro/glhit.h \
   $$PWD/build/libavogadro/include/avogadro/global.h \
   $$PWD/build/libavogadro/include/avogadro/glwidget.h \
   $$PWD/build/libavogadro/include/avogadro/idlist.h \
   $$PWD/build/libavogadro/include/avogadro/mesh.h \
   $$PWD/build/libavogadro/include/avogadro/meshgenerator.h \
   $$PWD/build/libavogadro/include/avogadro/molecule.h \
   $$PWD/build/libavogadro/include/avogadro/moleculefile.h \
   $$PWD/build/libavogadro/include/avogadro/navigate.h \
   $$PWD/build/libavogadro/include/avogadro/neighborlist.h \
   $$PWD/build/libavogadro/include/avogadro/obeigenconv.h \
   $$PWD/build/libavogadro/include/avogadro/painter.h \
   $$PWD/build/libavogadro/include/avogadro/painterdevice.h \
   $$PWD/build/libavogadro/include/avogadro/periodictableview.h \
   $$PWD/build/libavogadro/include/avogadro/plotaxis.h \
   $$PWD/build/libavogadro/include/avogadro/plotobject.h \
   $$PWD/build/libavogadro/include/avogadro/plotpoint.h \
   $$PWD/build/libavogadro/include/avogadro/plotwidget.h \
   $$PWD/build/libavogadro/include/avogadro/plugin.h \
   $$PWD/build/libavogadro/include/avogadro/pluginmanager.h \
   $$PWD/build/libavogadro/include/avogadro/primitive.h \
   $$PWD/build/libavogadro/include/avogadro/primitivelist.h \
   $$PWD/build/libavogadro/include/avogadro/protein.h \
   $$PWD/build/libavogadro/include/avogadro/pythonerror.h \
   $$PWD/build/libavogadro/include/avogadro/pythoninterpreter.h \
   $$PWD/build/libavogadro/include/avogadro/pythonscript.h \
   $$PWD/build/libavogadro/include/avogadro/residue.h \
   $$PWD/build/libavogadro/include/avogadro/textmatrixeditor.h \
   $$PWD/build/libavogadro/include/avogadro/tool.h \
   $$PWD/build/libavogadro/include/avogadro/toolgroup.h \
   $$PWD/build/libavogadro/include/avogadro/undosequence.h \
   $$PWD/build/libavogadro/include/avogadro/zmatrix.h \
   $$PWD/build/libavogadro/src/config.h \
   $$PWD/libavogadro/examples/c++/templateextension.h \
   $$PWD/libavogadro/examples/thirdPartyExtensions/01-HelloWorld/helloworlddialog.h \
   $$PWD/libavogadro/examples/thirdPartyExtensions/01-HelloWorld/helloworldextension.h \
   $$PWD/libavogadro/examples/thirdPartyExtensions/02-DynamicDisplay/dynamicdisplaydialog.h \
   $$PWD/libavogadro/examples/thirdPartyExtensions/02-DynamicDisplay/dynamicdisplayextension.h \
   $$PWD/libavogadro/examples/thirdPartyExtensions/03-ViewPlane/viewplaneextension.h \
   $$PWD/libavogadro/examples/thirdPartyExtensions/04-RotateSelection/rotateselectiondialog.h \
   $$PWD/libavogadro/examples/thirdPartyExtensions/04-RotateSelection/rotateselectionextension.h \
   $$PWD/libavogadro/examples/thirdPartyExtensions/05-ConformerPlot/conformerplotdialog.h \
   $$PWD/libavogadro/examples/thirdPartyExtensions/05-ConformerPlot/conformerplotextension.h \
   $$PWD/libavogadro/src/colors/atomindexcolor.h \
   $$PWD/libavogadro/src/colors/chargecolor.h \
   $$PWD/libavogadro/src/colors/customcolor.h \
   $$PWD/libavogadro/src/colors/distancecolor.h \
   $$PWD/libavogadro/src/colors/elementcolor.h \
   $$PWD/libavogadro/src/colors/residuecolor.h \
   $$PWD/libavogadro/src/colors/smartscolor.h \
   $$PWD/libavogadro/src/engines/axesengine.h \
   $$PWD/libavogadro/src/engines/bsdyengine.h \
   $$PWD/libavogadro/src/engines/cartoonengine.h \
   $$PWD/libavogadro/src/engines/cartoonmeshgenerator.h \
   $$PWD/libavogadro/src/engines/dipoleengine.h \
   $$PWD/libavogadro/src/engines/forceengine.h \
   $$PWD/libavogadro/src/engines/hbondengine.h \
   $$PWD/libavogadro/src/engines/labelengine.h \
   $$PWD/libavogadro/src/engines/polygonengine.h \
   $$PWD/libavogadro/src/engines/qtaimengine.h \
   $$PWD/libavogadro/src/engines/ribbonengine.h \
   $$PWD/libavogadro/src/engines/ringengine.h \
   $$PWD/libavogadro/src/engines/simplewireengine.h \
   $$PWD/libavogadro/src/engines/sphereengine.h \
   $$PWD/libavogadro/src/engines/stickengine.h \
   $$PWD/libavogadro/src/engines/surfaceengine.h \
   $$PWD/libavogadro/src/engines/wireengine.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/cell.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/debug.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/hall_symbol.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/kpoint.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/lattice.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/mathfunc.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/pointgroup.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/primitive.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/refinement.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/site_symmetry.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/sitesym_database.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/spacegroup.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/spg_database.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/spglib.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/spin.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/symmetry.h \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/tetrahedron_method.h \
   $$PWD/libavogadro/src/extensions/crystallography/ui/ceabstractdockwidget.h \
   $$PWD/libavogadro/src/extensions/crystallography/ui/ceabstracteditor.h \
   $$PWD/libavogadro/src/extensions/crystallography/ui/cecoordinateeditor.h \
   $$PWD/libavogadro/src/extensions/crystallography/ui/cematrixeditor.h \
   $$PWD/libavogadro/src/extensions/crystallography/ui/ceparametereditor.h \
   $$PWD/libavogadro/src/extensions/crystallography/ui/ceslabbuilder.h \
   $$PWD/libavogadro/src/extensions/crystallography/ui/cetranslatewidget.h \
   $$PWD/libavogadro/src/extensions/crystallography/ui/ceviewoptionswidget.h \
   $$PWD/libavogadro/src/extensions/crystallography/avospglib.h \
   $$PWD/libavogadro/src/extensions/crystallography/ceundo.h \
   $$PWD/libavogadro/src/extensions/crystallography/crystallographyextension.h \
   $$PWD/libavogadro/src/extensions/crystallography/crystalpastedialog.h \
   $$PWD/libavogadro/src/extensions/crystallography/stablecomparison.h \
   $$PWD/libavogadro/src/extensions/gl2ps/gl2ps.h \
   $$PWD/libavogadro/src/extensions/orca/orcaanalysedialog.h \
   $$PWD/libavogadro/src/extensions/orca/orcadata.h \
   $$PWD/libavogadro/src/extensions/orca/orcaextension.h \
   $$PWD/libavogadro/src/extensions/orca/orcainputdialog.h \
   $$PWD/libavogadro/src/extensions/orca/orcaspectra.h \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimcriticalpointlocator.h \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimcubature.h \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimextension.h \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimlsodaintegrator.h \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimmathutilities.h \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimodeintegrator.h \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimwavefunction.h \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimwavefunctionevaluator.h \
   $$PWD/libavogadro/src/extensions/quantuminput/abinitinputdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/daltoninputdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/gamessefpmatchdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/gamessextension.h \
   $$PWD/libavogadro/src/extensions/quantuminput/gamesshighlighter.h \
   $$PWD/libavogadro/src/extensions/quantuminput/gamessinputdata.h \
   $$PWD/libavogadro/src/extensions/quantuminput/gamessinputdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/gamessukinputdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/gaussianinputdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/inputdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/inputfileextension.h \
   $$PWD/libavogadro/src/extensions/quantuminput/lammpsinputdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/molproinputdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/mopacinputdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/nwcheminputdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/psi4inputdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/qcheminputdialog.h \
   $$PWD/libavogadro/src/extensions/quantuminput/teracheminputdialog.h \
   $$PWD/libavogadro/src/extensions/spectra/abstract_ir.h \
   $$PWD/libavogadro/src/extensions/spectra/cd.h \
   $$PWD/libavogadro/src/extensions/spectra/dos.h \
   $$PWD/libavogadro/src/extensions/spectra/ir.h \
   $$PWD/libavogadro/src/extensions/spectra/nmr.h \
   $$PWD/libavogadro/src/extensions/spectra/raman.h \
   $$PWD/libavogadro/src/extensions/spectra/spectradialog.h \
   $$PWD/libavogadro/src/extensions/spectra/spectraextension.h \
   $$PWD/libavogadro/src/extensions/spectra/spectratype.h \
   $$PWD/libavogadro/src/extensions/spectra/uv.h \
   $$PWD/libavogadro/src/extensions/spectra/vibrationextension.h \
   $$PWD/libavogadro/src/extensions/spectra/vibrationwidget.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/atom.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/basisset.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/basissetloader.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/cube.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/gamessukout.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/gamessus.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/gaussianfchk.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/gaussianset.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/molden.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/molecule.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/mopacaux.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/openqubeabi.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/orca.h \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/slaterset.h \
   $$PWD/libavogadro/src/extensions/surfaces/qtiocompressor/qtiocompressor.h \
   $$PWD/libavogadro/src/extensions/surfaces/approxmath.h \
   $$PWD/libavogadro/src/extensions/surfaces/htmldelegate.h \
   $$PWD/libavogadro/src/extensions/surfaces/molpro.h \
   $$PWD/libavogadro/src/extensions/surfaces/orbitalextension.h \
   $$PWD/libavogadro/src/extensions/surfaces/orbitalsettingsdialog.h \
   $$PWD/libavogadro/src/extensions/surfaces/orbitaltablemodel.h \
   $$PWD/libavogadro/src/extensions/surfaces/orbitalwidget.h \
   $$PWD/libavogadro/src/extensions/surfaces/surfacedialog.h \
   $$PWD/libavogadro/src/extensions/surfaces/surfaceextension.h \
   $$PWD/libavogadro/src/extensions/surfaces/vdwsurface.h \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/ANSR.h \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/Bitmap.h \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/Cell.h \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/Constants.h \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/Core3DMath.h \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/CoreConst.h \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/CrystalCell.h \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/eprintf.h \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/TubuleBasis.h \
   $$PWD/libavogadro/src/extensions/swcntbuilder/avotubegen.h \
   $$PWD/libavogadro/src/extensions/swcntbuilder/swcntbuilderextension.h \
   $$PWD/libavogadro/src/extensions/swcntbuilder/swcntbuilderwidget.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/character_table.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/context.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/elements.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/equivalence_set.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/geometry.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/linalg.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/msym.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/msym_error.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/orbital.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/permutation.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/point_group.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/symmetrize.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/symmetry.h \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/symop.h \
   $$PWD/libavogadro/src/extensions/symmetry/symmetryextension.h \
   $$PWD/libavogadro/src/extensions/animationdialog.h \
   $$PWD/libavogadro/src/extensions/animationextension.h \
   $$PWD/libavogadro/src/extensions/cartesianextension.h \
   $$PWD/libavogadro/src/extensions/conformersearchdialog.h \
   $$PWD/libavogadro/src/extensions/constraintsdialog.h \
   $$PWD/libavogadro/src/extensions/constraintsmodel.h \
   $$PWD/libavogadro/src/extensions/fileimportextension.h \
   $$PWD/libavogadro/src/extensions/forcefielddialog.h \
   $$PWD/libavogadro/src/extensions/forcefieldextension.h \
   $$PWD/libavogadro/src/extensions/gl2psextension.h \
   $$PWD/libavogadro/src/extensions/h2methylextension.h \
   $$PWD/libavogadro/src/extensions/highlighter.h \
   $$PWD/libavogadro/src/extensions/hydrogensextension.h \
   $$PWD/libavogadro/src/extensions/insertcommand.h \
   $$PWD/libavogadro/src/extensions/insertdnaextension.h \
   $$PWD/libavogadro/src/extensions/insertfragmentdialog.h \
   $$PWD/libavogadro/src/extensions/insertfragmentextension.h \
   $$PWD/libavogadro/src/extensions/insertpeptideextension.h \
   $$PWD/libavogadro/src/extensions/invertchiralextension.h \
   $$PWD/libavogadro/src/extensions/molecularpropextension.h \
   $$PWD/libavogadro/src/extensions/networkfetchextension.h \
   $$PWD/libavogadro/src/extensions/povpainter.h \
   $$PWD/libavogadro/src/extensions/povraydialog.h \
   $$PWD/libavogadro/src/extensions/povrayextension.h \
   $$PWD/libavogadro/src/extensions/propextension.h \
   $$PWD/libavogadro/src/extensions/propmodel.h \
   $$PWD/libavogadro/src/extensions/pythonterminal.h \
   $$PWD/libavogadro/src/extensions/selectextension.h \
   $$PWD/libavogadro/src/extensions/shaderextension.h \
   $$PWD/libavogadro/src/extensions/sortfiltertreeproxymodel.h \
   $$PWD/libavogadro/src/extensions/supercelldialog.h \
   $$PWD/libavogadro/src/extensions/supercellextension.h \
   $$PWD/libavogadro/src/extensions/trajvideomaker.h \
   $$PWD/libavogadro/src/extensions/vrmldialog.h \
   $$PWD/libavogadro/src/extensions/vrmlextension.h \
   $$PWD/libavogadro/src/extensions/vrmlpainter.h \
   $$PWD/libavogadro/src/extensions/wiitrackextension.h \
   $$PWD/libavogadro/src/python/moleculelist.h \
   $$PWD/libavogadro/src/tools/aligntool.h \
   $$PWD/libavogadro/src/tools/autoopttool.h \
   $$PWD/libavogadro/src/tools/autorotatetool.h \
   $$PWD/libavogadro/src/tools/bondcentrictool.h \
   $$PWD/libavogadro/src/tools/clickmeasuretool.h \
   $$PWD/libavogadro/src/tools/drawcommand.h \
   $$PWD/libavogadro/src/tools/drawtool.h \
   $$PWD/libavogadro/src/tools/eyecandy.h \
   $$PWD/libavogadro/src/tools/manipulatetool.h \
   $$PWD/libavogadro/src/tools/moveatomcommand.h \
   $$PWD/libavogadro/src/tools/navigatetool.h \
   $$PWD/libavogadro/src/tools/selectrotatetool.h \
   $$PWD/libavogadro/src/tools/skeletontree.h \
   $$PWD/libavogadro/src/tools/zmatrixdialog.h \
   $$PWD/libavogadro/src/tools/zmatrixmodel.h \
   $$PWD/libavogadro/src/tools/zmatrixtool.h \
   $$PWD/libavogadro/src/animation.h \
   $$PWD/libavogadro/src/atom.h \
   $$PWD/libavogadro/src/bond.h \
   $$PWD/libavogadro/src/camera.h \
   $$PWD/libavogadro/src/color.h \
   $$PWD/libavogadro/src/color3f.h \
   $$PWD/libavogadro/src/colorbutton.h \
   $$PWD/libavogadro/src/cube.h \
   $$PWD/libavogadro/src/cylinder_p.h \
   $$PWD/libavogadro/src/dockextension.h \
   $$PWD/libavogadro/src/dockwidget.h \
   $$PWD/libavogadro/src/elementdetail_p.h \
   $$PWD/libavogadro/src/elementitem_p.h \
   $$PWD/libavogadro/src/elementtranslator.h \
   $$PWD/libavogadro/src/engine.h \
   $$PWD/libavogadro/src/extension.h \
   $$PWD/libavogadro/src/fragment.h \
   $$PWD/libavogadro/src/glhit.h \
   $$PWD/libavogadro/src/global.h \
   $$PWD/libavogadro/src/glpainter_p.h \
   $$PWD/libavogadro/src/glwidget.h \
   $$PWD/libavogadro/src/idlist.h \
   $$PWD/libavogadro/src/mesh.h \
   $$PWD/libavogadro/src/meshgenerator.h \
   $$PWD/libavogadro/src/molecule.h \
   $$PWD/libavogadro/src/moleculefile.h \
   $$PWD/libavogadro/src/navigate.h \
   $$PWD/libavogadro/src/neighborlist.h \
   $$PWD/libavogadro/src/obeigenconv.h \
   $$PWD/libavogadro/src/painter.h \
   $$PWD/libavogadro/src/painterdevice.h \
   $$PWD/libavogadro/src/periodictablescene_p.h \
   $$PWD/libavogadro/src/periodictableview.h \
   $$PWD/libavogadro/src/plotaxis.h \
   $$PWD/libavogadro/src/plotobject.h \
   $$PWD/libavogadro/src/plotpoint.h \
   $$PWD/libavogadro/src/plotwidget.h \
   $$PWD/libavogadro/src/plugin.h \
   $$PWD/libavogadro/src/pluginmanager.h \
   $$PWD/libavogadro/src/primitive.h \
   $$PWD/libavogadro/src/primitivelist.h \
   $$PWD/libavogadro/src/protein.h \
   $$PWD/libavogadro/src/pythonengine_p.h \
   $$PWD/libavogadro/src/pythonerror.h \
   $$PWD/libavogadro/src/pythonextension_p.h \
   $$PWD/libavogadro/src/pythoninterpreter.h \
   $$PWD/libavogadro/src/pythonscript.h \
   $$PWD/libavogadro/src/pythonthread_p.h \
   $$PWD/libavogadro/src/pythontool_p.h \
   $$PWD/libavogadro/src/readfilethread_p.h \
   $$PWD/libavogadro/src/residue.h \
   $$PWD/libavogadro/src/sphere_p.h \
   $$PWD/libavogadro/src/surfacemeshgenerator.h \
   $$PWD/libavogadro/src/textmatrixeditor.h \
   $$PWD/libavogadro/src/textrenderer_p.h \
   $$PWD/libavogadro/src/tool.h \
   $$PWD/libavogadro/src/toolgroup.h \
   $$PWD/libavogadro/src/undosequence.h \
   $$PWD/libavogadro/src/zmatrix.h \
   $$PWD/libavogadro/tests/modeltest.h

SOURCES = \
   $$PWD/avogadro/src/projectdelegates/atomdelegate.cpp \
   $$PWD/avogadro/src/projectdelegates/bonddelegate.cpp \
   $$PWD/avogadro/src/projectdelegates/labeldelegate.cpp \
   $$PWD/avogadro/src/projectdelegates/moleculedelegate.cpp \
   $$PWD/avogadro/src/projectdelegates/residuedelegate.cpp \
   $$PWD/avogadro/src/projectdelegates/selectiondelegate.cpp \
   $$PWD/avogadro/src/aboutdialog.cpp \
   $$PWD/avogadro/src/addenginedialog.cpp \
   $$PWD/avogadro/src/application.cpp \
   $$PWD/avogadro/src/detachedview.cpp \
   $$PWD/avogadro/src/editcommands.cpp \
   $$PWD/avogadro/src/enginecolorswidget.cpp \
   $$PWD/avogadro/src/engineitemdelegate.cpp \
   $$PWD/avogadro/src/engineitemmodel.cpp \
   $$PWD/avogadro/src/enginelistview.cpp \
   $$PWD/avogadro/src/engineprimitiveswidget.cpp \
   $$PWD/avogadro/src/engineviewwidget.cpp \
   $$PWD/avogadro/src/flattabwidget.cpp \
   $$PWD/avogadro/src/glgraphicsview.cpp \
   $$PWD/avogadro/src/importdialog.cpp \
   $$PWD/avogadro/src/main.cpp \
   $$PWD/avogadro/src/mainwindow.cpp \
   $$PWD/avogadro/src/pluginitemmodel.cpp \
   $$PWD/avogadro/src/pluginlistview.cpp \
   $$PWD/avogadro/src/pluginsettings.cpp \
   $$PWD/avogadro/src/primitiveitemmodel.cpp \
   $$PWD/avogadro/src/primitivetreeview.cpp \
   $$PWD/avogadro/src/projecttreeeditor.cpp \
   $$PWD/avogadro/src/projecttreeitem.cpp \
   $$PWD/avogadro/src/projecttreemodel.cpp \
   $$PWD/avogadro/src/projecttreemodeldelegate.cpp \
   $$PWD/avogadro/src/savedialog.cpp \
   $$PWD/avogadro/src/settingsdialog.cpp \
   $$PWD/avogadro/src/updatecheck.cpp \
   $$PWD/avogadro/src/updatedialog.cpp \
   $$PWD/build/CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c \
   $$PWD/build/CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/build/CMakeFiles/feature_tests.c \
   $$PWD/build/CMakeFiles/feature_tests.cxx \
   $$PWD/build/libavogadro/src/moc_pythonengine_p.cxx \
   $$PWD/build/libavogadro/src/moc_pythonerror.cxx \
   $$PWD/build/libavogadro/src/moc_pythonextension_p.cxx \
   $$PWD/build/libavogadro/src/moc_pythontool_p.cxx \
   $$PWD/build/libavogadro/src/qrc_pythontool.cxx \
   $$PWD/build/libavogadro/src/staticplugins.cpp \
   $$PWD/libavogadro/examples/c++/templateextension.cpp \
   $$PWD/libavogadro/examples/thirdPartyExtensions/01-HelloWorld/helloworlddialog.cpp \
   $$PWD/libavogadro/examples/thirdPartyExtensions/01-HelloWorld/helloworldextension.cpp \
   $$PWD/libavogadro/examples/thirdPartyExtensions/02-DynamicDisplay/dynamicdisplaydialog.cpp \
   $$PWD/libavogadro/examples/thirdPartyExtensions/02-DynamicDisplay/dynamicdisplayextension.cpp \
   $$PWD/libavogadro/examples/thirdPartyExtensions/03-ViewPlane/viewplaneextension.cpp \
   $$PWD/libavogadro/examples/thirdPartyExtensions/04-RotateSelection/rotateselectiondialog.cpp \
   $$PWD/libavogadro/examples/thirdPartyExtensions/04-RotateSelection/rotateselectionextension.cpp \
   $$PWD/libavogadro/examples/thirdPartyExtensions/05-ConformerPlot/conformerplotdialog.cpp \
   $$PWD/libavogadro/examples/thirdPartyExtensions/05-ConformerPlot/conformerplotextension.cpp \
   $$PWD/libavogadro/src/colors/atomindexcolor.cpp \
   $$PWD/libavogadro/src/colors/chargecolor.cpp \
   $$PWD/libavogadro/src/colors/customcolor.cpp \
   $$PWD/libavogadro/src/colors/distancecolor.cpp \
   $$PWD/libavogadro/src/colors/elementcolor.cpp \
   $$PWD/libavogadro/src/colors/residuecolor.cpp \
   $$PWD/libavogadro/src/colors/smartscolor.cpp \
   $$PWD/libavogadro/src/engines/axesengine.cpp \
   $$PWD/libavogadro/src/engines/bsdyengine.cpp \
   $$PWD/libavogadro/src/engines/cartoonengine.cpp \
   $$PWD/libavogadro/src/engines/cartoonmeshgenerator.cpp \
   $$PWD/libavogadro/src/engines/dipoleengine.cpp \
   $$PWD/libavogadro/src/engines/forceengine.cpp \
   $$PWD/libavogadro/src/engines/hbondengine.cpp \
   $$PWD/libavogadro/src/engines/labelengine.cpp \
   $$PWD/libavogadro/src/engines/polygonengine.cpp \
   $$PWD/libavogadro/src/engines/qtaimengine.cpp \
   $$PWD/libavogadro/src/engines/ribbonengine.cpp \
   $$PWD/libavogadro/src/engines/ringengine.cpp \
   $$PWD/libavogadro/src/engines/simplewireengine.cpp \
   $$PWD/libavogadro/src/engines/sphereengine.cpp \
   $$PWD/libavogadro/src/engines/stickengine.cpp \
   $$PWD/libavogadro/src/engines/surfaceengine.cpp \
   $$PWD/libavogadro/src/engines/wireengine.cpp \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/cell.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/debug.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/hall_symbol.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/kpoint.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/lattice.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/mathfunc.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/pointgroup.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/primitive.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/refinement.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/site_symmetry.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/sitesym_database.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/spacegroup.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/spg_database.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/spglib.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/spglib_f.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/spin.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/symmetry.c \
   $$PWD/libavogadro/src/extensions/crystallography/spglib/tetrahedron_method.c \
   $$PWD/libavogadro/src/extensions/crystallography/ui/ceabstractdockwidget.cpp \
   $$PWD/libavogadro/src/extensions/crystallography/ui/ceabstracteditor.cpp \
   $$PWD/libavogadro/src/extensions/crystallography/ui/cecoordinateeditor.cpp \
   $$PWD/libavogadro/src/extensions/crystallography/ui/cematrixeditor.cpp \
   $$PWD/libavogadro/src/extensions/crystallography/ui/ceparametereditor.cpp \
   $$PWD/libavogadro/src/extensions/crystallography/ui/ceslabbuilder.cpp \
   $$PWD/libavogadro/src/extensions/crystallography/ui/cetranslatewidget.cpp \
   $$PWD/libavogadro/src/extensions/crystallography/ui/ceviewoptionswidget.cpp \
   $$PWD/libavogadro/src/extensions/crystallography/avospglib.cpp \
   $$PWD/libavogadro/src/extensions/crystallography/ceundo.cpp \
   $$PWD/libavogadro/src/extensions/crystallography/crystallographyextension.cpp \
   $$PWD/libavogadro/src/extensions/crystallography/crystalpastedialog.cpp \
   $$PWD/libavogadro/src/extensions/gl2ps/gl2ps.c \
   $$PWD/libavogadro/src/extensions/gl2ps/gl2psTest.c \
   $$PWD/libavogadro/src/extensions/gl2ps/gl2psTestSimple.c \
   $$PWD/libavogadro/src/extensions/orca/orcaanalysedialog.cpp \
   $$PWD/libavogadro/src/extensions/orca/orcadata.cpp \
   $$PWD/libavogadro/src/extensions/orca/orcaextension.cpp \
   $$PWD/libavogadro/src/extensions/orca/orcainputdialog.cpp \
   $$PWD/libavogadro/src/extensions/orca/orcaspectra.cpp \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimcriticalpointlocator.cpp \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimcubature.cpp \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimextension.cpp \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimlsodaintegrator.cpp \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimmathutilities.cpp \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimodeintegrator.cpp \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimwavefunction.cpp \
   $$PWD/libavogadro/src/extensions/qtaim/qtaimwavefunctionevaluator.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/abinitinputdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/daltoninputdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/gamessefpmatchdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/gamessextension.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/gamesshighlighter.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/gamessinputdata.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/gamessinputdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/gamessukinputdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/gaussianinputdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/inputdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/inputfileextension.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/lammpsinputdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/molproinputdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/mopacinputdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/nwcheminputdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/psi4inputdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/qcheminputdialog.cpp \
   $$PWD/libavogadro/src/extensions/quantuminput/teracheminputdialog.cpp \
   $$PWD/libavogadro/src/extensions/spectra/abstract_ir.cpp \
   $$PWD/libavogadro/src/extensions/spectra/cd.cpp \
   $$PWD/libavogadro/src/extensions/spectra/dos.cpp \
   $$PWD/libavogadro/src/extensions/spectra/ir.cpp \
   $$PWD/libavogadro/src/extensions/spectra/nmr.cpp \
   $$PWD/libavogadro/src/extensions/spectra/raman.cpp \
   $$PWD/libavogadro/src/extensions/spectra/spectradialog.cpp \
   $$PWD/libavogadro/src/extensions/spectra/spectraextension.cpp \
   $$PWD/libavogadro/src/extensions/spectra/spectratype.cpp \
   $$PWD/libavogadro/src/extensions/spectra/uv.cpp \
   $$PWD/libavogadro/src/extensions/spectra/vibrationextension.cpp \
   $$PWD/libavogadro/src/extensions/spectra/vibrationwidget.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/atom.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/basisset.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/basissetloader.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/cube.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/gamessukout.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/gamessus.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/gaussianfchk.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/gaussianset.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/molden.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/molecule.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/mopacaux.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/orca.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/qube.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/openqube/slaterset.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/qtiocompressor/qtiocompressor.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/htmldelegate.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/molpro.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/orbitalextension.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/orbitalsettingsdialog.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/orbitaltablemodel.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/orbitalwidget.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/surfacedialog.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/surfaceextension.cpp \
   $$PWD/libavogadro/src/extensions/surfaces/vdwsurface.cpp \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/ANSR.cpp \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/Bitmap.c \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/Cell.cpp \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/Core3DMath.c \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/CrystalCell.cpp \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/diamond.cpp \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/eprintf.c \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/fcc.cpp \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/graphite.cpp \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/TubeGen.cpp \
   $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen/TubuleBasis.cpp \
   $$PWD/libavogadro/src/extensions/swcntbuilder/avotubegen.cpp \
   $$PWD/libavogadro/src/extensions/swcntbuilder/swcntbuilderextension.cpp \
   $$PWD/libavogadro/src/extensions/swcntbuilder/swcntbuilderwidget.cpp \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/examples/example.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/character_table.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/context.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/elements.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/equivalence_set.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/geometry.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/linalg.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/msym.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/msym_error.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/orbital.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/permutation.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/point_group.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/symmetrize.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/symmetry.c \
   $$PWD/libavogadro/src/extensions/symmetry/libmsym/src/symop.c \
   $$PWD/libavogadro/src/extensions/symmetry/symmetryextension.cpp \
   $$PWD/libavogadro/src/extensions/animationdialog.cpp \
   $$PWD/libavogadro/src/extensions/animationextension.cpp \
   $$PWD/libavogadro/src/extensions/cartesianextension.cpp \
   $$PWD/libavogadro/src/extensions/conformersearchdialog.cpp \
   $$PWD/libavogadro/src/extensions/constraintsdialog.cpp \
   $$PWD/libavogadro/src/extensions/constraintsmodel.cpp \
   $$PWD/libavogadro/src/extensions/fileimportextension.cpp \
   $$PWD/libavogadro/src/extensions/forcefielddialog.cpp \
   $$PWD/libavogadro/src/extensions/forcefieldextension.cpp \
   $$PWD/libavogadro/src/extensions/gl2psextension.cpp \
   $$PWD/libavogadro/src/extensions/h2methylextension.cpp \
   $$PWD/libavogadro/src/extensions/highlighter.cpp \
   $$PWD/libavogadro/src/extensions/hydrogensextension.cpp \
   $$PWD/libavogadro/src/extensions/insertcommand.cpp \
   $$PWD/libavogadro/src/extensions/insertdnaextension.cpp \
   $$PWD/libavogadro/src/extensions/insertfragmentdialog.cpp \
   $$PWD/libavogadro/src/extensions/insertfragmentextension.cpp \
   $$PWD/libavogadro/src/extensions/insertpeptideextension.cpp \
   $$PWD/libavogadro/src/extensions/invertchiralextension.cpp \
   $$PWD/libavogadro/src/extensions/molecularpropextension.cpp \
   $$PWD/libavogadro/src/extensions/networkfetchextension.cpp \
   $$PWD/libavogadro/src/extensions/povpainter.cpp \
   $$PWD/libavogadro/src/extensions/povraydialog.cpp \
   $$PWD/libavogadro/src/extensions/povrayextension.cpp \
   $$PWD/libavogadro/src/extensions/propextension.cpp \
   $$PWD/libavogadro/src/extensions/propmodel.cpp \
   $$PWD/libavogadro/src/extensions/pythonterminal.cpp \
   $$PWD/libavogadro/src/extensions/selectextension.cpp \
   $$PWD/libavogadro/src/extensions/shaderextension.cpp \
   $$PWD/libavogadro/src/extensions/sortfiltertreeproxymodel.cpp \
   $$PWD/libavogadro/src/extensions/supercelldialog.cpp \
   $$PWD/libavogadro/src/extensions/supercellextension.cpp \
   $$PWD/libavogadro/src/extensions/trajvideomaker.cpp \
   $$PWD/libavogadro/src/extensions/vrmldialog.cpp \
   $$PWD/libavogadro/src/extensions/vrmlextension.cpp \
   $$PWD/libavogadro/src/extensions/vrmlpainter.cpp \
   $$PWD/libavogadro/src/extensions/wiitrackextension.cpp \
   $$PWD/libavogadro/src/python/animation.cpp \
   $$PWD/libavogadro/src/python/atom.cpp \
   $$PWD/libavogadro/src/python/bond.cpp \
   $$PWD/libavogadro/src/python/camera.cpp \
   $$PWD/libavogadro/src/python/color.cpp \
   $$PWD/libavogadro/src/python/cube.cpp \
   $$PWD/libavogadro/src/python/eigen.cpp \
   $$PWD/libavogadro/src/python/elementtranslator.cpp \
   $$PWD/libavogadro/src/python/engine.cpp \
   $$PWD/libavogadro/src/python/extension.cpp \
   $$PWD/libavogadro/src/python/fragment.cpp \
   $$PWD/libavogadro/src/python/glwidget.cpp \
   $$PWD/libavogadro/src/python/main.cpp \
   $$PWD/libavogadro/src/python/mesh.cpp \
   $$PWD/libavogadro/src/python/meshgenerator.cpp \
   $$PWD/libavogadro/src/python/molecule.cpp \
   $$PWD/libavogadro/src/python/moleculefile.cpp \
   $$PWD/libavogadro/src/python/moleculelist.cpp \
   $$PWD/libavogadro/src/python/navigate.cpp \
   $$PWD/libavogadro/src/python/neighborlist.cpp \
   $$PWD/libavogadro/src/python/painter.cpp \
   $$PWD/libavogadro/src/python/painterdevice.cpp \
   $$PWD/libavogadro/src/python/periodictableview.cpp \
   $$PWD/libavogadro/src/python/plugin.cpp \
   $$PWD/libavogadro/src/python/pluginmanager.cpp \
   $$PWD/libavogadro/src/python/primitive.cpp \
   $$PWD/libavogadro/src/python/primitivelist.cpp \
   $$PWD/libavogadro/src/python/qlist.cpp \
   $$PWD/libavogadro/src/python/qstring.cpp \
   $$PWD/libavogadro/src/python/residue.cpp \
   $$PWD/libavogadro/src/python/sip.cpp \
   $$PWD/libavogadro/src/python/std_vector.cpp \
   $$PWD/libavogadro/src/python/swig.cpp \
   $$PWD/libavogadro/src/python/tool.cpp \
   $$PWD/libavogadro/src/python/toolgroup.cpp \
   $$PWD/libavogadro/src/tools/aligntool.cpp \
   $$PWD/libavogadro/src/tools/autoopttool.cpp \
   $$PWD/libavogadro/src/tools/autorotatetool.cpp \
   $$PWD/libavogadro/src/tools/bondcentrictool.cpp \
   $$PWD/libavogadro/src/tools/clickmeasuretool.cpp \
   $$PWD/libavogadro/src/tools/drawcommand.cpp \
   $$PWD/libavogadro/src/tools/drawtool.cpp \
   $$PWD/libavogadro/src/tools/eyecandy.cpp \
   $$PWD/libavogadro/src/tools/manipulatetool.cpp \
   $$PWD/libavogadro/src/tools/moveatomcommand.cpp \
   $$PWD/libavogadro/src/tools/navigatetool.cpp \
   $$PWD/libavogadro/src/tools/selectrotatetool.cpp \
   $$PWD/libavogadro/src/tools/skeletontree.cpp \
   $$PWD/libavogadro/src/tools/zmatrixdialog.cpp \
   $$PWD/libavogadro/src/tools/zmatrixmodel.cpp \
   $$PWD/libavogadro/src/tools/zmatrixtool.cpp \
   $$PWD/libavogadro/src/animation.cpp \
   $$PWD/libavogadro/src/atom.cpp \
   $$PWD/libavogadro/src/bond.cpp \
   $$PWD/libavogadro/src/camera.cpp \
   $$PWD/libavogadro/src/color.cpp \
   $$PWD/libavogadro/src/colorbutton.cpp \
   $$PWD/libavogadro/src/cube.cpp \
   $$PWD/libavogadro/src/cylinder_p.cpp \
   $$PWD/libavogadro/src/dockextension.cpp \
   $$PWD/libavogadro/src/dockwidget.cpp \
   $$PWD/libavogadro/src/elementdetail_p.cpp \
   $$PWD/libavogadro/src/elementitem_p.cpp \
   $$PWD/libavogadro/src/elementtranslator.cpp \
   $$PWD/libavogadro/src/engine.cpp \
   $$PWD/libavogadro/src/extension.cpp \
   $$PWD/libavogadro/src/fragment.cpp \
   $$PWD/libavogadro/src/glhit.cpp \
   $$PWD/libavogadro/src/global.cpp \
   $$PWD/libavogadro/src/glpainter_p.cpp \
   $$PWD/libavogadro/src/glwidget.cpp \
   $$PWD/libavogadro/src/idlist.cpp \
   $$PWD/libavogadro/src/mesh.cpp \
   $$PWD/libavogadro/src/meshgenerator.cpp \
   $$PWD/libavogadro/src/molecule.cpp \
   $$PWD/libavogadro/src/moleculefile.cpp \
   $$PWD/libavogadro/src/navigate.cpp \
   $$PWD/libavogadro/src/neighborlist.cpp \
   $$PWD/libavogadro/src/painter.cpp \
   $$PWD/libavogadro/src/periodictablescene_p.cpp \
   $$PWD/libavogadro/src/periodictableview.cpp \
   $$PWD/libavogadro/src/plotaxis.cpp \
   $$PWD/libavogadro/src/plotobject.cpp \
   $$PWD/libavogadro/src/plotpoint.cpp \
   $$PWD/libavogadro/src/plotwidget.cpp \
   $$PWD/libavogadro/src/plugin.cpp \
   $$PWD/libavogadro/src/pluginmanager.cpp \
   $$PWD/libavogadro/src/primitive.cpp \
   $$PWD/libavogadro/src/primitivelist.cpp \
   $$PWD/libavogadro/src/protein.cpp \
   $$PWD/libavogadro/src/pythonengine_p.cpp \
   $$PWD/libavogadro/src/pythonerror.cpp \
   $$PWD/libavogadro/src/pythonextension_p.cpp \
   $$PWD/libavogadro/src/pythoninterpreter.cpp \
   $$PWD/libavogadro/src/pythonscript.cpp \
   $$PWD/libavogadro/src/pythontool_p.cpp \
   $$PWD/libavogadro/src/readfilethread_p.cpp \
   $$PWD/libavogadro/src/residue.cpp \
   $$PWD/libavogadro/src/sphere_p.cpp \
   $$PWD/libavogadro/src/textmatrixeditor.cpp \
   $$PWD/libavogadro/src/textrenderer_p.cpp \
   $$PWD/libavogadro/src/tool.cpp \
   $$PWD/libavogadro/src/toolgroup.cpp \
   $$PWD/libavogadro/src/undosequence.cpp \
   $$PWD/libavogadro/src/zmatrix.cpp \
   $$PWD/libavogadro/tests/drawcommandtest.cpp \
   $$PWD/libavogadro/tests/hydrogenscommandtest.cpp \
   $$PWD/libavogadro/tests/modeltest.cpp \
   $$PWD/libavogadro/tests/moleculebench.cpp \
   $$PWD/libavogadro/tests/moleculefiletest.cpp \
   $$PWD/libavogadro/tests/moleculetest.cpp \
   $$PWD/libavogadro/tests/neighborlisttest.cpp \
   $$PWD/libavogadro/tests/primitivemodeltest.cpp

INCLUDEPATH = \
    $$PWD/avogadro/src \
    $$PWD/avogadro/src/projectdelegates \
    $$PWD/build/avogadro/src \
    $$PWD/build/libavogadro/include/avogadro \
    $$PWD/build/libavogadro/src \
    $$PWD/libavogadro/examples/c++ \
    $$PWD/libavogadro/examples/thirdPartyExtensions/01-HelloWorld \
    $$PWD/libavogadro/examples/thirdPartyExtensions/02-DynamicDisplay \
    $$PWD/libavogadro/examples/thirdPartyExtensions/03-ViewPlane \
    $$PWD/libavogadro/examples/thirdPartyExtensions/04-RotateSelection \
    $$PWD/libavogadro/examples/thirdPartyExtensions/05-ConformerPlot \
    $$PWD/libavogadro/src \
    $$PWD/libavogadro/src/colors \
    $$PWD/libavogadro/src/engines \
    $$PWD/libavogadro/src/extensions \
    $$PWD/libavogadro/src/extensions/crystallography \
    $$PWD/libavogadro/src/extensions/crystallography/spglib \
    $$PWD/libavogadro/src/extensions/crystallography/ui \
    $$PWD/libavogadro/src/extensions/gl2ps \
    $$PWD/libavogadro/src/extensions/orca \
    $$PWD/libavogadro/src/extensions/qtaim \
    $$PWD/libavogadro/src/extensions/quantuminput \
    $$PWD/libavogadro/src/extensions/spectra \
    $$PWD/libavogadro/src/extensions/surfaces \
    $$PWD/libavogadro/src/extensions/surfaces/openqube \
    $$PWD/libavogadro/src/extensions/surfaces/qtiocompressor \
    $$PWD/libavogadro/src/extensions/swcntbuilder \
    $$PWD/libavogadro/src/extensions/swcntbuilder/tubegen \
    $$PWD/libavogadro/src/extensions/symmetry \
    $$PWD/libavogadro/src/extensions/symmetry/libmsym/src \
    $$PWD/libavogadro/src/python \
    $$PWD/libavogadro/src/tools \
    $$PWD/libavogadro/tests

#DEFINES = 

